footprint: [[0.343,0.18], [0.343,-0.18], [-0.38,-0.18], [-0.38,0.18]] # MINI
publish_frequency: 1.0
transform_tolerance: 1.0
map_type: costmap


static_layer:
  enabled: true
  map_topic: map

obstacle_layer_lidar2scan:
  enabled: true
  obstacle_range: 4
  raytrace_range: 20
  track_unknown_space: true
  combination_method: 0
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    # topic `scan ` was published by the driver of LIDAR
    # topic `scan1` was published by the driver of pointcloud_to_laserscan
    topic: /scan1
    sensor_frame: base_link
    marking: true
    clearing: true
    expected_update_rate: 0

obstacle_layer_stereo2scan:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 5
  track_unknown_space: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    # topic `scan ` was published by the driver of LIDAR
    # topic `scan2` was published by the driver of d435
    topic: /scan2
    sensor_frame: base_link
    marking: true
    clearing: true
    expected_update_rate: 0

rgbd_obstacle_layer:
  enabled:                  true
  voxel_decay:              15    # seconds if linear, e^n if exponential
  decay_model:              0     # 0=linear, 1=exponential, -1=persistent
  voxel_size:               0.05  # meters
  track_unknown_space:      true  # default space is known
  max_obstacle_height:      2.0   # meters
  unknown_threshold:        15    # voxel height
  mark_threshold:           0     # voxel height
  update_footprint_enabled: true
  combination_method:       1     # 1=max, 0=override
  obstacle_range:           3.0   # meters
  origin_z:                 0.0   # meters
  publish_voxel_map:        true  # default off
  transform_tolerance:      0.2   # seconds
  mapping_mode:             false # default off, saves map not for navigation
  map_save_duration:        60    # default 60s, how often to autosave
  observation_sources:      rgbd1_mark rgbd1_clear
  rgbd1_mark:
    data_type: PointCloud2
    topic: /rslidar_points
    marking: true
    clearing: false
    min_obstacle_height: 0.3     # default 0, meters
    max_obstacle_height: 2.0     # default 3, meters
    expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
    inf_is_valid: false          # default false, for laser scans
    voxel_filter: false          # default off, apply voxel filter to sensor, recommend on
    clear_after_reading: true    # default false, clear the buffer after the layer gets readings from it
  rgbd1_clear:
    enabled: true                #default true, can be toggled on/off with associated service call
    data_type: PointCloud2
    topic: /rslidar_points
    marking: false
    clearing: true
    max_z: 8.0                  # default 0, meters
    min_z: 1.0                  # default 10, meters
    vertical_fov_angle: 0.523   # default 0.7, radians. For 3D lidars it's the symmetric FOV about the planar axis.
    vertical_fov_padding: 0.05    # 3D Lidar only. Default 0, in meters 
    horizontal_fov_angle: 6.29  # 3D lidar scanners like the VLP16 have 360 deg horizontal FOV.
    decay_acceleration: 5.0     # default 0, 1/s^2. 
    model_type: 1               # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar

global_inflation_layer:
  enabled: true
  cost_scaling_factor: 1.75
  inflation_radius: 0.5

local_inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.25