# footprint: [[0.51, -0.25], [0.51, 0.25], [-0.51, 0.25], [-0.51, -0.25]] # Pro
# footprint: [[0.45,-0.225], [0.45,0.225], [-0.45,0.225], [-0.45,-0.225]] # JYL
footprint: [[0.343,0.18], [0.343,-0.18], [-0.38,-0.18], [-0.38,0.18]] # Mini
publish_frequency: 1.0
transform_tolerance: 1.0
map_type: costmap


static_layer:
  enabled: true
  map_topic: map

obstacle_layer1:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 5.5
  track_unknown_space: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    # topic `scan ` was published by the driver of velodyne
    # topic `scan1` was published by the driver of velodyne
    topic: /scan1
    sensor_frame: base_link
    marking: true
    clearing: true
    expected_update_rate: 0

obstacle_layer2:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 5.5
  track_unknown_space: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    # topic `scan ` was published by the driver of velodyne
    # topic `scan1` was published by the driver of velodyne
    # topic `scan2` was published by the driver of d435
    topic: /scan2
    sensor_frame: base_link
    marking: true
    clearing: true
    expected_update_rate: 0

global_inflation_layer:
  enabled: true
  cost_scaling_factor: 1.75
  inflation_radius: 1.0

local_inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.5