local_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  transform_tolerance: 2.0
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 7
  height: 7
  resolution: 0.03


  plugins:
    - {name: obstacle_layer1, type: "costmap_2d::ObstacleLayer"}
    - {name: obstacle_layer2, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
